### ISSUE TITLE
TODO for v1.0

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/livelog-android#1]
- [x] デフォルト UI の LiveLog 化
  - [x] アプリアイコン
  - [x] FAB 除去
  - [x] NavigationDrawer 変更
  - [x] テーマカラー変更
- [x] トップ画面の実装
  - [x] 曲リストを表示するフラグメントを作成
  - [x] 曲リストのアイテムのデザイン
  - [x] 曲の取得
  - [x] 曲の表示
  - [x] 無限スクロール
  - [x] 検索 → ホーム<s>（検索は別アクティビティで実装）</s>
- [x] Lives の実装
  - [x] 年度ごとにタイトルを追加
- [x] Members の実装
- [x] resource の整備
- [x] 曲検索
  - [x] 検索時ドロワーを開けないようにする
  - [x] 検索結果がなかった際のフィードバック
- [x] 通信中のフィードバック
- [x] <s>エラー後再取得</s>スワイプでリロード
- [x] メンバー「現役のみ」トグル
- [x] 画面の回転問題
- [x] ライブ詳細
- [x] メンバー詳細
- [x] 曲詳細
  - [x] 動画の閲覧
  - [x] 詳細の表示
  - [x] 動画のアクセス権限のコントロールとサムネイル
  - [x] 横画面でフルスクリーン
  - [x] サムネイルの表示
- [x] `const` を使う
- [x] メンバーリストのトグルのフィードバック
- [x] アプリリース
